apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-ytvj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-ytvj
    app.kubernetes.io/part-of: test-app-dqcv
  name: maven-hello-world-ytvj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: maven-hello-world-ytvj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: maven-hello-world-ytvj
    spec:
      containers:
      - image: quay.io/susdas_quay_org/build-e2e-olfe-tenant/test-app-dqcv/maven-hello-world-ytvj@sha256:eb2451dcac3b1e6d54caeb3bb39aa62eac9b55ecd08e2d7278559a236cf4628d
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
